### ISSUE TITLE
general object (de)serialization for Network stream read and write method

### ISSUE THREAD

**Issue by cisar2218** [cisar2218/Plutonication#6]
## Problem description
One of usecases that Plutonication could have cover is sending of data in format: `sendMessage(messageCode, string, object)`, where object is **general c# object** (see the method format in image bellow).
![image](https://user-images.githubusercontent.com/69775422/218711529-394a27a5-a638-4bc4-a021-659ae297d70d.png)
According to resources that I studied this pretty much cannot be done reliably using standard serialization methods. Additional thing is that [`BinaryFormatter Class`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.serialization.formatters.binary.binaryformatter?view=net-7.0) is not completely safe to use.
## Current state
Implemented in [this](https://github.com/cisar2218/Plutonication/tree/6-general-object-deserialization-for-network-stream-read-and-write-method) branch using  [`BinaryFormatter Class`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.serialization.formatters.binary.binaryformatter?view=net-7.0). This implementation is not reliable and behave strange at deserialization end.
## Conclusion
Therefore this issues requires more study and time. I would also consider use completely different approach to serialization. Maybe do some step between `object` and `byte[]` format.

**Comment by cisar2218** [comment]
[Daniel_97 suggested approach](https://stackoverflow.com/a/73194655/15709464) that i was thinking about in my prev comment. May study and try this approach.

**Comment by RostislavLitovkin** [comment]
Not relevant anymore.
